apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: staging
spec:
  project: default
  source:
    repoURL: https://github.com/jmeridth/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./environment-promotion/envs/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
  
